name: ducker
description: Determine if your app is in review
version: 0.1.0
homepage: https://github.com/lukepighetti/ducker

platforms:
  ios:

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  package_info_plus: ^8.1.4
  pub_semver: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
